---
# CI environment override — no volume mounts, code + deps baked into image
services:
  php:
    build:
      context: .
      target: frankenphp_ci
    environment:
      APP_ENV: test
      MERCURE_EXTRA_DIRECTIVES: demo
